---
name: Foo Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get all changed apps
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          json: "true"
          files: "apps/**"
          dir_names: "true"
          dir_names_max_depth: "2"

      - name: Print changed files
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}"

  build:
    needs: changed-files
    strategy:
      matrix:
        app: "${{ needs.changed-files.outputs.all_changed_files }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          tag_prefix: "${{ matrix.app }}-"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.app }}/**
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}