name: Jira is the force of freedom

on:
  release:
    types: [published]
jobs:
  create-jira-release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: Rorychan/jira-releases-action@v1
        with:
          jira-server: 'https://dannbohn.atlassian.com'
          jira-email: 'dannbohn@gmail.com'
          jira-api-token: ${{ secrets.JIRA_TOKEN }}
          project-name: 'KAN'
          release-name: ${{ github.event.release.name }}