---
name: Preview

on:
  pull_request:
    branches: [ "main" ]
    types: [labeled, opened, synchronize, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PULL_REQUEST_URL: "null"

jobs:
  preview:
    if: contains( github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    env:
      K8S_DEPLOYMENT_REPO: whereismyjetpack/gitops

    steps:
      - name: Wait on Workflow
        uses: lucasssvaz/wait-on-workflow@v1
        with:
          workflow: main.yml
          max-wait: 3
          interval: 5
          timeout: 60
          sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: imranismail/setup-kustomize@v2
      - name: Checkout Deployment Repo
        if: contains( github.event.pull_request.labels.*.name, 'preview')
        uses: actions/checkout@v4
        with:
          repository: ${{ env.K8S_DEPLOYMENT_REPO }}
          token: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
          path: deployment

      - name: Create a new preview from template
        if: contains( github.event.pull_request.labels.*.name, 'preview')
        run: |
          cd deployment
          cp -rf env/fastify-url-shortner/preview env/fastify-url-shortner/preview-${{github.event.number}}
          cd env/fastify-url-shortner/preview-${{github.event.number}}
          kustomize edit set namespace url-shortner-preview-${{github.event.number}}
          kustomize edit add patch --kind Ingress --name fastify-url-shortner --patch '[{"op": "replace", "path": "/spec/rules/0/host", "value":"foo-${{github.event.number}}"}]'

      - name: Promote to ${{ env.K8S_DEPLOYMENT_REPO }} - preview
        if: contains( github.event.pull_request.labels.*.name, 'preview')
        uses: kustomize-everything/action-promote@v4.3.3
        with:
          images: |-
            [
              {
                "name": "fastify-url-shortner",
                "newName": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}",
                "newTag": "${{ github.event.pull_request.head.sha || github.sha }}",
                "overlays": ["env/fastify-url-shortner/preview-${{github.event.number}}"]
              }
            ]
          target-repo: ${{ env.K8S_DEPLOYMENT_REPO }}
          promotion-method: push
          working-directory: deployment
          github-token: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
          git-commit-user: 'whereismyjetpack'
          git-commit-email: 'mail@mail.mail'



