name: Promote to Staging

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  GH_TOKEN: ${{ github.token }}
  IMAGE_NAME: ${{ github.repository }}
  PULL_REQUEST_URL: "null"
  K8S_DEPLOYMENT_REPO: whereismyjetpack/gitops

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for workflow
        uses: ArcticLampyrid/action-wait-for-workflow@v1.2.0
        with:
          workflow: main.yml
  
      # - name: Wait on Workflow
      #   id: wait-on-workflow
      #   uses: lucasssvaz/wait-on-workflow@v1
      #   with:
      #     workflow: main.yml
      #     max-wait: 3
      #     interval: 5
      #     timeout: 60
      #     sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - id: version
        uses: fabien-marty/github-next-semantic-version-action@v1
        with:
          github-token: ${{ github.token }} # Let's use the default value of the current workflow
          repository: ${{ github.repository }} # Let's use the default value of the current workflow
          repository-owner: ${{ github.repository_owner }} # Let's use the default value of the current workflow
        
      - name: Check release
        id: check
        run: |
          echo "Latest version is ${{ steps.version.outputs.latest-version }}"
          echo "Next version is ${{ steps.version.outputs.next-version }}"
          if [ $(git rev-list -n 1 ${{ steps.version.outputs.latest-version}}) = $(git rev-list -n 1 HEAD) ]; then 
            changed=false >> "$GITHUB_OUTPUT"
          else
            changed=true >> "$GITHUB_OUTPUT"
          fi

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Create Release
        if: ${{steps.check.outputs.changed == 'true' }}
        run: |
          gh release create ${{ steps.version.outputs.next-version }} --generate-notes

  promote:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout Deployment Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.K8S_DEPLOYMENT_REPO }}
          token: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
          path: deployment

      - name: Promote
        uses: kustomize-everything/action-promote@v4.2.1
        with:
          images: |-
            [
              {
                "name": "fastify-url-shortner",
                "fromOverlay": "env/fastify-url-shortner/integration",
                "overlays": ["env/fastify-url-shortner/staging"]
              }
            ]
          target-repo: ${{ env.K8S_DEPLOYMENT_REPO }}
          promotion-method: push
          working-directory: deployment
          github-token: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
          git-commit-user: 'whereismyjetpack'
          git-commit-email: 'mail@mail.mail'



