on:
  push:
    tags:        
    - '*'
jobs:
  jira-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Medsien/release-to-jira@main
        with:
          jira_server: 'https://dannbohn.atlassian.net'
          jira_project: 'KAN'
          jira_user: 'dannbohn@gmail.com'
          jira_token: '${{ secrets.JIRA_TOKEN }}'