name: Update

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [sandbox0, sandbox1, sandbox2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Update ${{ matrix.channel }}
        env:
          CHANNEL: ${{ matrix.channel }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git rev-parse HEAD
          echo "${{ github.run_number }} (base: $(git rev-parse HEAD))" > "${CHANNEL}.txt"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add "${CHANNEL}.txt"
          git commit -m "Update $CHANNEL"
          branch="${CHANNEL}-$(date +%s)"
          git push origin HEAD:"$branch"
          gh pr create --head "$branch" --title "Update ${CHANNEL}" \
            --body "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          gh pr merge "$branch" --merge